alerts:
  image: thoughtworksturkey/marketwatcher-alert-service
  environment:
      - CASSANDRA_NODES=db:9042
  links:
    - "db"
  ports:
    - "10100:10100"
  entrypoint:
    - "start.sh"

db:
  image: cassandra:2.2
